printWidth: 120
tabWidth: 4
useTabs: false
semi: false
singleQuote: false
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
proseWrap: "always"
singleAttributePerLine: true
