name: Deploy to S3

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install and build
              uses: withastro/action@v3
              with:
                  path: .
                  node-version: 20
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
                aws-region: ap-northeast-1
            - name: Deploy to S3
              working-directory: dist
              run: aws s3 sync . s3://${{ secrets.BUCKET_NAME }}
