name: Deploy to S3

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

env:
  NODE_VERSION: '20'
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install and build
              uses: withastro/action@v3
              with:
                  path: .
                  node-version: ${{ env.NODE_VERSION }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
                aws-region: ap-northeast-1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODE_VERSION }}
                node-version-file: cdk/package.json
                cache-dependency-path: cdk/package-lock.json

            - name: npm install
              working-directory: cdk
              run: npm ci

          - name: Deploy to S3
            working-directory: cdk
            run: npx cdk deploy
